pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Restore') {
            steps {
                bat 'dotnet restore'
            }
        }

        stage('Build') {
            steps {
                bat 'dotnet build -c Release'
            }
        }

        stage('Publish') {
            steps {
                bat '''
                dotnet publish -c Release -o "C:\\Users\\karth\\OneDrive\\Desktop\\Goal\\24_Jenkins\\JenkinsDeploy\\ExpenseTracker"
                '''
            }
        }
    }
}
